### PR TITLE
test: snapshot testing research

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**
Add the Storybook framework to Nx:
```
ng add @nrwl/storybook@12 --uiFramework=@storybook/angular --skip-confirmation
```

Add Storybook configuration for a specific project:
```
nx g @nrwl/angular:storybook-configuration indicators --configureCypress --generateStories --generateCypressSpecs
```

Delete any unwanted specs and stories.

Install [@percy/cli](https://github.com/percy/cli).
Install and implement [@percy/cypress](https://github.com/percy/percy-cypress).

Run e2e against storybook:
```
export PERCY_TOKEN=<token-from-browserstack.com> && export PERCY_BRANCH=local && ./node_modules/.bin/percy exec -- nx run indicators-e2e:e2e
```

Serve storybook instance:
```
nx run indicators:storybook
```

[AB#2085604](https://dev.azure.com/blackbaud/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/2085604)
[AB#2087762](https://dev.azure.com/blackbaud/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/2087762)

### CODE REVIEW

**Comment by johnhwhite** [comment]
Test comment

**Comment by johnhwhite** [comment]
[Storybook preview](https://blackbaud.github.io/skyux-pr/)

**Comment by johnhwhite** [comment]
[Storybook preview](https://blackbaud.github.io/skyux-pr/)

**Comment by blackbaud-sky-build-user** [comment]
[Storybook preview](https://blackbaud.github.io/skyux-pr-preview/46/) for #46

**Comment by blackbaud-sky-build-user** [comment]
[Storybook preview](https://blackbaud.github.io/skyux-pr-preview/46/storybook/)

Component Storybooks:

- [ag-grid-storybook](https://blackbaud.github.io/skyux-pr-preview/46/storybooks/ag-grid-storybook/)
- [flyout-storybook](https://blackbaud.github.io/skyux-pr-preview/46/storybooks/flyout-storybook/)
- [indicators-storybook](https://blackbaud.github.io/skyux-pr-preview/46/storybooks/indicators-storybook/)
- [lists-storybook](https://blackbaud.github.io/skyux-pr-preview/46/storybooks/lists-storybook/)
- [popovers-storybook](https://blackbaud.github.io/skyux-pr-preview/46/storybooks/popovers-storybook/)
- [tabs-storybook](https://blackbaud.github.io/skyux-pr-preview/46/storybooks/tabs-storybook/)

**Pull request closed without merging**
